//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int AddressId { get; set; }
        public int CityFrom { get; set; }
        public string AddressFrom { get; set; }
        public Nullable<int> CityTo { get; set; }
        public string AddressTo { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Accurancy { get; set; }
        public string AddressFromBlock { get; set; }
        public string AddressFromPorch { get; set; }
        public string AddressToBlock { get; set; }
        public string AddressToPorch { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
