//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Address = new HashSet<Address>();
            this.Address1 = new HashSet<Address>();
        }
    
        public int CityId { get; set; }
        public string Name { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Address> Address1 { get; set; }
    }
}
