//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ClientId { get; set; }
        public string Phone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsActive { get; set; }
        public string ActivateCode { get; set; }
        public Nullable<int> SmsSentCount { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
