//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Car = new HashSet<Car>();
            this.OrderCompany = new HashSet<OrderCompany>();
            this.PricesRate = new HashSet<PricesRate>();
            this.User = new HashSet<User>();
        }
    
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Car> Car { get; set; }
        public virtual ICollection<OrderCompany> OrderCompany { get; set; }
        public virtual ICollection<PricesRate> PricesRate { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
