//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProperties
    {
        public OrderProperties()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int OrderPropertiesId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int OrderClass { get; set; }
        public int Priority { get; set; }
        public bool Childer { get; set; }
        public bool Nosmoking { get; set; }
        public bool Animal { get; set; }
        public bool English { get; set; }
        public bool Card { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
