//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNote
    {
        public int OrderNoteId { get; set; }
        public int OrderId { get; set; }
        public int NoteType { get; set; }
        public Nullable<int> Vote { get; set; }
        public string UserComment { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
