//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderId { get; set; }
        public int ClientId { get; set; }
        public int Expr2 { get; set; }
        public Nullable<int> CarId { get; set; }
        public System.DateTime Deadline { get; set; }
        public int AddressId { get; set; }
        public Nullable<int> Tariff { get; set; }
        public Nullable<double> EstimatedPrice { get; set; }
        public bool IsPrepaid { get; set; }
        public bool IsPlanned { get; set; }
        public Nullable<System.DateTime> PlannedOn { get; set; }
        public int Status { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeAssigned { get; set; }
        public Nullable<System.DateTime> TimeArrived { get; set; }
        public Nullable<System.DateTime> TimeInCar { get; set; }
        public Nullable<System.DateTime> TimeDone { get; set; }
        public Nullable<System.DateTime> TimeCanceled { get; set; }
        public Nullable<int> CanceledBy { get; set; }
        public Nullable<int> CancelCause { get; set; }
        public Nullable<double> FinalPrice { get; set; }
        public string UserComment { get; set; }
        public string TaxiComment { get; set; }
        public int CityFrom { get; set; }
        public string AddressFrom { get; set; }
        public Nullable<int> CityTo { get; set; }
        public string AddressTo { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Accurancy { get; set; }
        public int NoteType { get; set; }
        public Nullable<int> Vote { get; set; }
        public string Expr1 { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string Phone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int OrderClass { get; set; }
        public int Priority { get; set; }
        public bool Childer { get; set; }
        public bool Nosmoking { get; set; }
        public bool Animal { get; set; }
        public bool English { get; set; }
        public bool Card { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public Nullable<int> NrOfSeats { get; set; }
        public string CarNumber { get; set; }
        public string DriverName { get; set; }
    }
}
